---

- hosts: localhost
  connection: local
  gather_facts: false
  
  credentials:
        node_ip: 1.2.3.4
        api_token: ey123
  
  vars:
       vm_name: 10.38.X.X

  tasks:
        
      - name: node remove
        rubrik_physical_host:
          hostname: "{{ vm_name }}"
          action: delete
          
          
          
          
---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
       vm_name: 10.38.X.X

  tasks:
        
      - name: node remove
        rubrik_physical_host:
          hostname: "{{ vm_name }}"
          action: delete
