---

- hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
       credentials:
           node_ip: sin-sup-brik-00.sin.support.rubrik.com
           api_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkODc1ZWM5Mi0wY2M4LTRkM2UtOGE1Mi03NGY1OGRjMzM0ZTciLCJpc01mYVJlbWVtYmVyVG9rZW4iOmZhbHNlLCJpc3MiOiIwY2Q2ZTQ2ZS01NzRiLTQxODMtYWNmYS0xNDgxOTk2MmZjZWYiLCJpYXQiOjE2NTc2MTg2NTUsImp0aSI6IjkxMjNlOThjLTBiZTYtNDNmNC1hMmI5LTM1NzdiYzY1ZGMxNSJ9.VepeAiOr0g_CyIavKwCXet7bFuIJXX2FPnum0DyGtNI

  tasks:
        
      - debug:
            mgs: "Running a call for API- GET"
            
      - name: node list get
        rubrik_get:
            provider: "{{ credentials }}"
            api_version: v1
            api_endpoint: "/fileset_template?operating_system_type=UnixLike&sort_by=name&sort_order=asc"
        register: results


    
    
    
    