---

- hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
       credentials:
           node_ip: 1.2.3.4
           api_token: ey

  tasks:
        
      - debug:
            mgs: "Running a call for API- GET"
            
      - name: node list get
        rubrik_get:
            provider: "{{ credentials }}"
            api_version: v1
            api_endpoint: "/fileset_template?operating_system_type=UnixLike&sort_by=name&sort_order=asc"
        register: results


    
    
    
    
