---

- hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
       vm_name: 10.38.X.X 
       credentials:
            node_ip: 1.2.3.4
            api_token: ey123


  tasks:
        
      - name: node remove
        rubrik_physical_host:
          provider: "{{ credentials }}"
          hostname: "{{ vm_name }}"
          action: add
