---

- hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
       vm_name: 10.38.200.8  
       credentials:
            node_ip: sin-sup-brik-00.sin.support.rubrik.com
            api_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkODc1ZWM5Mi0wY2M4LTRkM2UtOGE1Mi03NGY1OGRjMzM0ZTciLCJpc01mYVJlbWVtYmVyVG9rZW4iOmZhbHNlLCJpc3MiOiIwY2Q2ZTQ2ZS01NzRiLTQxODMtYWNmYS0xNDgxOTk2MmZjZWYiLCJpYXQiOjE2NTc2MTg2NTUsImp0aSI6IjkxMjNlOThjLTBiZTYtNDNmNC1hMmI5LTM1NzdiYzY1ZGMxNSJ9.VepeAiOr0g_CyIavKwCXet7bFuIJXX2FPnum0DyGtNI


  tasks:
        
      - name: node remove
        rubrik_physical_host:
          provider: "{{ credentials }}"
          hostname: "{{ vm_name }}"
          action: add